city: Los Angeles
tz: America/Los_Angeles
host: [insteon, insteon2]
switches:
    lights: [B2,B3,B4,B5]
    livingroom: 1E.3F.0D
    study: [B12,B13]
    desk: B12
    stairs: B5
    frontlight: 1E.EF.E1
    backlight: 1E.F1.48
    outside: B6,B7
    garage: B8
    fountain: B1
    pbed: J1
    lawn: J2
    orchard: J3
    yard: J4
    herbs: j5
    fence: j6
    splanter: j7
    nplanter: j8
    rosebed: j9
    frontplanters: j10
    avocado: j11
    jungle: j12
    frontyard: j13
    driveway: j14
    frontdrip: j15
    parkway: j16
schedule:

    -   {switch: lawn, queue: w,          from: now + 1, to: + 10,  if: 'ordinal % 1 == 0'}  
    -   {switch: orchard, queue: w,       from: + 1,    to: + 10,  if: 'ordinal % 3 == 0'} 
    -   {switch: herbs, queue: w,         from: + 1,    to: + 8,   if: 'ordinal % 4 == 0'} 
    -   {switch: fence, queue: w,         from: + 1,    to: + 8,   if: 'ordinal % 4 == 0'}  
    -   {switch: splanter, queue: w,      from: + 1,    to: + 8,   if: 'ordinal % 1 == 0'} 
    -   {switch: nplanter, queue: w,      from: + 1,    to: + 8,   if: 'ordinal % 1 == 0'} 
    -   {switch: frontplanters, queue: w, from: + 1,    to: + 12,  if: 'ordinal % 2 == 0'}  
    -   {switch: avocado, queue: w,       from: + 1,    to: + 20,  if: 'ordinal % 15 == 0'} 
    -   {switch: jungle, queue: w,        from: + 1,    to: + 10,  if: 'ordinal % 4 == 0'} 
    -   {switch: frontyard, queue: w,     from: + 1,    to: + 7,   if: 'ordinal % 4 == 0'} 
    -   {switch: parkway, queue: w,       from: + 1,    to: + 8,   if: 'ordinal % 4 == 0'}      
    -   {switch: frontdrip, queue: w,     from: + 1,    to: + 20,  if: 'ordinal % 1 == 0'}   
    -   {switch: pbed,      queue: w,     from: + 1,    to: + 60,  if: 'ordinal % 2 == 0'}   
    
    -   {switch: frontlight, queue: l, from: now + 1, to: '11:15' }
    -   {switch: backlight, queue: l, from: now + 1,to: '11:15' }
    -   {switch: study, queue: l, from: now + 1 ,to: '11:20' }        
    
        
    