#! /bin/env python 

import os, shutil

import esbinsteon
import argparse

dest = '/etc/insteon.yaml'
cf = os.path.join(os.path.dirname(esbinsteon.__file__),'config','insteon.yaml')

parser = argparse.ArgumentParser(description='Install the schedule file')

parser.add_argument('--force', '-f', action='store_const', const=True, help="Overwrite existing scehdule")

args = parser.parse_args()



if not os.path.exists(dest) or args.force:
    shutil.copy(cf, dest)
    print "Installed {}".format(dest)

    